# Intentamos realizar una operación que podría generar un error
num1 = int(input("Ingrese un número: "))
num2 = int(input("Ingrese otro número: "))
resultado = num1 / num2
print(f"El resultado de la división es: {resultado}")